### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Image Super Resolution Dataset/train_images/train/X/'

### ISSUE THREAD

**Issue by cycheuk** [titu1994/Image-Super-Resolution#19]
Hello there, 
I try to run the tests.py by using SRCNN model, but it popped out the error.
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Image Super Resolution Dataset/train_images/train/X/'
And there are no train_images/train/X/ files, should I create it by myself?

**Comment by titu1994** [comment]
Run img_utils.py and it will generate the dataset for you

**Comment by Combo819** [comment]
Do you solve this problem now? The image dataset created by img_utils.py is in train_images/train/validation/X/, rather than train_images/train/X/. I copy the files into train_images/train/X/ by myself, but encounter new problem showed below.
@cycheuk @titu1994 


C:\Users\combo\AppData\Local\Programs\Python\Python36\python.exe C:/Users/combo/Image-Super-Resolution-master/tests.py
C:\Users\combo\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\combo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Training model : ImageSuperResolutionModel
2018-04-20 19:32:14.936752: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Epoch 1/250
Found 20 images.
Traceback (most recent call last):
  File "C:/Users/combo/Image-Super-Resolution-master/tests.py", line 47, in <module>
    sr.fit(nb_epochs=250)
  File "C:\Users\combo\Image-Super-Resolution-master\models.py", line 516, in fit
    return super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)
  File "C:\Users\combo\Image-Super-Resolution-master\models.py", line 122, in fit
    validation_steps=val_count // batch_size + 1)
  File "C:\Users\combo\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\combo\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 2224, in fit_generator
    class_weight=class_weight)
  File "C:\Users\combo\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1877, in train_on_batch
    class_weight=class_weight)
  File "C:\Users\combo\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1476, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\combo\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (32, 32, 3) but got array with shape (64, 64, 3)

Process finished with exit code 1

**Comment by JeffSaa** [comment]
Anyone solve this? I getting the same error
