### ISSUE TITLE
Permission  denied

### ISSUE THREAD

**Issue by Paraside90** [titu1994/Image-Super-Resolution#2]
hello, i came across the following problem when i tried your code.  I tried it in cmd prompt and spyder, and it showed the same error (in windows 7). I have given the folder all permissoin. The following is the error message:

runfile('D:/hdd/work/Image-Super-Resolution-master/main.py', args='"d:/hdd/work/Image-Super-Resolution-master/input_images/"', wdir='D:/hdd/work/Image-Super-Resolution-master')
Reloaded modules: img_utils, models, advanced
Traceback (most recent call last):

  File "<ipython-input-11-05bdd5a09cc9>", line 1, in <module>
    runfile('D:/hdd/work/Image-Super-Resolution-master/main.py', args='"d:/hdd/work/Image-Super-Resolution-master/input_images/"', wdir='D:/hdd/work/Image-Super-Resolution-master')

  File "D:\hdd\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "D:\hdd\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/hdd/work/Image-Super-Resolution-master/main.py", line 50, in <module>
    model.upscale(path, save_intermediate=save, mode=mode, patch_size=patch_size, suffix=suffix)

  File "D:\hdd\work\Image-Super-Resolution-master\models.py", line 133, in upscale
    true_img = imread(img_path, mode='RGB')

  File "D:\hdd\Anaconda3\lib\site-packages\scipy\misc\pilutil.py", line 154, in imread
    im = Image.open(name)

  File "D:\hdd\Anaconda3\lib\site-packages\PIL\Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")

PermissionError: [Errno 13] Permission denied: 'd:/hdd/work/Image-Super-Resolution-master/input_images/'

I hope you can give me some solutions!

**Comment by titu1994** [comment]
@Paraside90 Main.py is used only to upscale a single image. Not a directory. Put the full path of the image that you want to upscale.

If you want to train a model, use test.py, uncomment the parts that you want and then execute that with the path of the dataset.

**Comment by Paraside90** [comment]
Thank you for your reply.  Now, I'm preparing training the model, but it give the following errors:
runfile('D:/hdd/work/Image-Super-Resolution-master/tests.py', wdir='D:/hdd/work/Image-Super-Resolution-master')
Using Theano backend.
Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN not available)
Training model : DeepDenoiseSR
Epoch 1/180
Found 23296 images.
Traceback (most recent call last):

  File "<ipython-input-2-697e9257f4b4>", line 1, in <module>
    runfile('D:/hdd/work/Image-Super-Resolution-master/tests.py', wdir='D:/hdd/work/Image-Super-Resolution-master')

  File "D:\hdd\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "D:\hdd\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/hdd/work/Image-Super-Resolution-master/tests.py", line 63, in <module>
    ddsr.fit(nb_epochs=180)

  File "D:\hdd\work\Image-Super-Resolution-master\models.py", line 602, in fit
    super(DeepDenoiseSR, self).fit(batch_size, nb_epochs, save_history, history_fn)

  File "D:\hdd\work\Image-Super-Resolution-master\models.py", line 100, in fit
    nb_val_samples=val_count)

  File "D:\hdd\Anaconda3\lib\site-packages\keras\engine\training.py", line 1461, in fit_generator
    class_weight=class_weight)

  File "D:\hdd\Anaconda3\lib\site-packages\keras\engine\training.py", line 1233, in train_on_batch
    check_batch_dim=True)

  File "D:\hdd\Anaconda3\lib\site-packages\keras\engine\training.py", line 979, in _standardize_user_data
    exception_prefix='model input')

  File "D:\hdd\Anaconda3\lib\site-packages\keras\engine\training.py", line 111, in standardize_input_data
    str(array.shape))

Exception: Error when checking model input: expected input_1 to have shape (None, 32, 32, 3) but got array with shape (128, 3, 32, 32)
I'm new to keras, so i hope you can give me some solutions again. thank you!

**Comment by titu1994** [comment]
@Paraside90 That was a mistake in how the generator loaded the images. I pushed a commit just now to support the tensorflow dim ordering. Please download the repo again or simply copy paste the code from https://github.com/titu1994/Image-Super-Resolution/blob/master/img_utils.py into your copy of img_utils.py
