### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by impactcolor** [titu1994/Image-Super-Resolution#23]
Hi is there any doc on requirements?  I'm running tensor flow with keras and I get errors on both python 2.7 and python 3.5.

Any help would be appreciated, thank you!

**Comment by titu1994** [comment]
Could you specify what error you got? I tested this with TF backend, Keras 2.1.3 and Python 3.5

**Comment by impactcolor** [comment]
I ran python main.py input_images/testme.jpg and got
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import models
  File "/root/Image-Super-Resolution/models.py", line 12, in <module>
    import img_utils
  File "/root/Image-Super-Resolution/img_utils.py", line 7, in <module>
    import cv
ImportError: No module named 'cv'

**Comment by impactcolor** [comment]
@titu1994 error above

**Comment by titu1994** [comment]
Open cv is a requirement for this. Try conda install opencv

**Comment by impactcolor** [comment]
@titu1994 Still no luck I reinstalled everything to make sure I'm running correctly:

Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import models
  File "/root/Image-Super-Resolution/models.py", line 12, in <module>
    import img_utils
  File "/root/Image-Super-Resolution/img_utils.py", line 7, in <module>
    import cv
ModuleNotFoundError: No module named 'cv'

CV installed through conda I checked it and it's there.  I ran import cv2

**Comment by titu1994** [comment]
On Windows, opencv has many problems during installation. It should be import cv2. 

Even then, there can be some internal import problems from open cv itself.

**Comment by impactcolor** [comment]
@titu1994 Hi I got it working I was having problems with my cv.  One file was set to "import cv" once I fixed that it worked.  When I scale to 5 it gives this error:

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (Unable to open file: name = 'weights/distilledresnetsr 5x.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

running this: python main.py input_images/testme.jpg --scale=5

any ideas?

**Comment by titu1994** [comment]
That's because there are no pretrained models for scale 5. You'll have to train your own, or pass the scale 2 model 3 (8x scale) times and then downscale.

**Comment by impactcolor** [comment]
I'm confused on this one: model 3.  These are the options: python main.py "imgpath" --model="type", where type = sr, esr, dsr, ddsr
which would it be?

**Comment by priyanshu2210** [comment]
@titu1994 I am having the same issue, as I am new to this I am unable to process your recommendations of March 16 , Thank you so much for uploading source code It helps me understanding a few details. Thank you again for helping.
