### ISSUE TITLE
ValueError: could not broadcast input array from shape (32,32,3) into shape (64,64,3)

### ISSUE THREAD

**Issue by cycheuk** [titu1994/Image-Super-Resolution#28]
Hello there, I also encountered this problem.
Traceback (most recent call last):
  File "tests.py", line 47, in <module>
    sr.fit(nb_epochs=250)
  File "/home/tensor/Checuk/Image-Super-Resolution/models.py", line 516, in fit
    return super(ImageSuperResolutionModel, self).fit(batch_size, nb_epochs, save_history, history_fn)
  File "/home/tensor/Cheuk/Image-Super-Resolution/models.py", line 122, in fit
    validation_steps=val_count // batch_size + 1)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2194, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "/home/tensor/Cheuk/Image-Super-Resolution/img_utils.py", line 301, in image_generator
    batch_x[i] = img
ValueError: could not broadcast input array from shape (32,32,3) into shape (64,64,3)

I tried to change the def create_model, but it didn't help, and I also tried to change the parameters of the img_utils. 
If you have time, please help me fix this problem. Thanks.

**Comment by rafariva** [comment]
what was the solution?

**Comment by JeffSaa** [comment]
Same here

**Comment by JeffSaa** [comment]
@titu1994
