### ISSUE TITLE
expected input_1 to have shape

### ISSUE THREAD

**Issue by ManoaNosea** [titu1994/Image-Super-Resolution#30]
```
λ python tests_dsr.py
Using TensorFlow backend.
Training model : DenoisingAutoEncoderSR
2018-06-17 08:36:39.645569: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Epoch 1/250
Found 11156 images.
Traceback (most recent call last):
  File "tests_dsr.py", line 63, in <module>
    dsr.fit(nb_epochs=250)
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\titu1994\Image-Super-Resolution-master\models.py", line 607, in fit
    return super(DenoisingAutoEncoderSR, self).fit(batch_size, nb_epochs, save_history, history_fn)
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\titu1994\Image-Super-Resolution-master\models.py", line 122, in fit
    validation_steps=val_count // batch_size + 1)
  File "C:\Python35\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Python35\lib\site-packages\keras\engine\training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Python35\lib\site-packages\keras\engine\training_generator.py", line 191, in fit_generator
    class_weight=class_weight)
  File "C:\Python35\lib\site-packages\keras\engine\training.py", line 1214, in train_on_batch
    class_weight=class_weight)
  File "C:\Python35\lib\site-packages\keras\engine\training.py", line 754, in _standardize_user_data
    exception_prefix='input')
  File "C:\Python35\lib\site-packages\keras\engine\training_utils.py", line 136, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (32, 32, 3) but got array with shape (64, 64, 3)
```
what the problem ?

**Comment by titu1994** [comment]
The data is input is 64x64, whereas the model expects 32x32. You'll need to resize the image with the flag in img_utils.py.
