### ISSUE TITLE
->Model syntax error

### ISSUE THREAD

**Issue by spikopat** [titu1994/Image-Super-Resolution#34]
Traceback (most recent call last):
  File "drive/PythonOrtam/SuperResolution/main.py", line 1, in <module>
    import models
  File "/content/drive/PythonOrtam/SuperResolution/models.py", line 70
    def create_model(self, height=32, width=32, channels=3, load_weights=False, batch_size=128) -> Model:
                                                                                                ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "drive/PythonOrtam/SuperResolution/main.py", line 1, in <module>
    import models
  File "/content/drive/PythonOrtam/SuperResolution/models.py", line 277
    def _evaluate(sr_model: BaseSuperResolutionModel, validation_dir, scale_pred=False):
                          ^
SyntaxError: invalid syntax

I have some errors. Can you help me please?

**Comment by titu1994** [comment]
You're using python 2.7. It doesn't support the " -> Model" and ": BaseSuperResolutionModel" type inference from Python 3. 

Remove those parts and it should work.
