### ISSUE TITLE
Expected binary or unicode string, got (None, 8, 8, 3)

### ISSUE THREAD

**Issue by maabdelghaffar** [titu1994/Image-Super-Resolution#4]
Hello, I have tried to run the code exactly as you specified using the following command:

python main.py "/home/moataz/Downloads/Image-Super-Resolution-master/input_images/t10.bmp"

But it gave me the following error at the end:
Not sure if I am doing something wrong 

Using TensorFlow backend.
Old Size :  (129, 142, 3)
New Size : (284, 258, 3)
Number of patches = 69527, Patch Shape = (8, 8)
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    model.upscale(path, save_intermediate=save, mode=mode, patch_size=patch_size, suffix=suffix)
  File "/home/moataz/Downloads/Image-Super-Resolution-master/models.py", line 180, in upscale
    model = self.create_model(img_height, img_width, load_weights=True)
  File "/home/moataz/Downloads/Image-Super-Resolution-master/models.py", line 531, in create_model
    level2_2 = Deconvolution2D(self.n1, 3, 3, activation=u'relu', output_shape=output_shape, border_mode=u'same')(level2_1)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 514, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 656, in call
    filter_shape=self.W_shape)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1674, in deconv2d
    padding=padding)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 278, in conv2d_transpose
    output_shape_ = ops.convert_to_tensor(output_shape, name="output_shape")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 657, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 180, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 422, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/compat.py", line 64, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got (None, 8, 8, 3)

**Comment by titu1994** [comment]
Sorry for the late reply.

This seems to be a python 2 error (unicode formatting error are usually unicode errors), and I haven't tested this repo on 2.7. Sorry, but if you find a fix, please add a pull request.

**Comment by maabdelghaffar** [comment]
Actually everything worked fine after i changed to Theano backend
